FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

# build xmrig
RUN git clone https://github.com/ZhangGaoxing/xmrig-mo.git --depth=1
# enable MSR
ARG TARGETPLATFORM
RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
        echo "$TARGETPLATFORM, install tools"; \
        apt install -y msr-tools kmod; \
        cd /xmrig-mo/scripts; \
        sh randomx_boost.sh; \
    else \
        echo "$TARGETPLATFORM, skip."; \
    fi
# build
WORKDIR /xmrig-mo/build
RUN cmake .. && \
    make -j$(nproc)
RUN mkdir /xmrig /xmrig/configs && \
    cp xmrig /xmrig && \
    cp ../src/config.json /xmrig/configs

# build xmrig-cuda
WORKDIR /
RUN git clone https://github.com/xmrig/xmrig-cuda.git --depth=1
WORKDIR /xmrig-cuda/build
RUN cmake .. -DCUDA_LIB=/usr/local/cuda/lib64/stubs/libcuda.so -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda && \
    make -j$(nproc)
RUN cp libxmrig-cuda.so /xmrig

# cleanup
RUN rm -rf /xmrig-mo /xmrig-cuda
RUN apt-get purge -y git build-essential cmake && \
    apt-get autoremove -y

WORKDIR /xmrig
CMD ["/xmrig/xmrig", "--config=/xmrig/configs/config.json"]
